FROM ubuntu:14.04
MAINTAINER mukki
#plugins
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install apache2
RUN apt-get -y install php5 
RUN apt-get -y install php5-mysql wget nano
WORKDIR /opt
RUN wget https://wordpress.org/latest.tar.gz
RUN tar -xzffff 
#ADD wp-config.php /var/www/html/wp-config.php
EXPOSE 80 3306 
ENTRYPOINT service apache2 restart && sleep 3600
